# Generated by Django 5.0.4 on 2024-04-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assesment_Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100, unique=True)),
                ('subject_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('sydney_participants', models.IntegerField()),
                ('sydney_percentile', models.FloatField()),
                ('assesment_area_id', models.IntegerField()),
                ('awards_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('correct_answer_percentage_per_class', models.FloatField()),
                ('correct_answers', models.CharField(max_length=1)),
                ('student_id', models.IntegerField()),
                ('participant', models.IntegerField()),
                ('student_score', models.FloatField()),
                ('subject_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('year_level_name', models.CharField(max_length=100)),
                ('answer_id', models.IntegerField()),
                ('correct_answers_id', models.IntegerField()),
            ],
        ),
    ]
